#master:
#  persistence:
#    enabled: true
#    ## mariadb data Persistent Volume Storage Class
#    ## If defined, storageClassName: <storageClass>
#    ## If set to "-", storageClassName: "", which disables dynamic provisioning
#    ## If undefined (the default) or set to null, no storageClassName spec is
#    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
#    ##   GKE, AWS & OpenStack)
#    ##
#    storageClass: "gp2"
#    accessMode: ReadWriteOnce
#    size: 8Gi

 global:
   storageClass: gp2