apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mediawiki-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: mediawiki-db
  serviceName: mediawiki-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki-db
    spec:
      containers:
        - name: mediawiki-db
          image: bitnami/mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: MARIADB_USER
              value: bn_mediawiki
            - name: MARIADB_PASSWORD
              value: bitnami
            - name: MARIADB_DATABASE
              value: bitnami_mediawiki
          volumeMounts:
            - name: dbvol
              mountPath: /var/lib/mysql
              subPath: mysql
  volumeClaimTemplates:
    - metadata:
        name: dbvol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-db
  namespace: default
  labels:
    app: mediawiki-db
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mediawiki-db